# -*- coding: utf-8 -*-
"""On_line_PI_single_drone_animation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lEObFzsftxwqcBpB0alFW3fIAyhe9xPu

# Animation for On-Line Policy Iteration for the Multidimensional Assignment Problem

Animation of the algorithm from:
  "On-Line Policy Iteration for Finite-Horizon Deterministic Optimal Control
   with A Fixed Initial State" (Li, Chen, Li, Fan, Bertsekas, 2026)

Copyright (c) 2026 Fei Chen, Yuchao Li

The multidimensional assignment problem (Section 4.1):
  - $N+1$ layers $(N_0, ..., N_{N})$, each with $m$ nodes.
  - A grouping is a set of $(N+1)$ nodes, one per layer.  Its cost depends on the entire tuple $(j_0, j_1, ..., j_{N})$.
  - An $(N+1)$-dimensional assignment partitions all m*N nodes into $m$ disjoint groupings.  Its cost is the sum of grouping costs.
  - Goal: find the minimum-cost assignment.

Formulation as an $N$-stage optimal control problem:
  - Control $u_k$ is a permutation mapping layer-$k$ nodes to layer-$(k+1)$ nodes.
  - State $x_k = (u_0, ..., u_{k-1})$ records the arcs chosen so far.
  - Stage costs $g_k$ = 0 for $k < N$;  terminal cost $g_N(x_N)$ is the assignment cost determined by $(u_0, ..., u_{N-1})$.
  - A policy $\pi^\ell$ is represented by the stored trajectory; the generator $G$ replays it (consistent by construction).

Key insight for the minimization at stage k:
  Given the prefix $(u_0^{\ell+1}, ..., u_{k-1}^{\ell+1})$ and the suffix from policy $\pi^\ell$ as $(u_{k+1}^\ell, ..., u_{N-2}^\ell)$, the only free variable is the
  permutation $u_k$.  The total cost decomposes as a sum over $m$ groupings, and each grouping's contribution depends only on which node it visits at layer $k+1$ (the rest of the path is fixed).  So choosing $u_k$ amounts to
  solving a bipartite matching (linear assignment) problem, where the weight of assigning node a at layer $k$ to node $b$ at layer $k+1$ equals the grouping cost of the path that passes through a at layer $k$ and $b$ at layer $k+1$.
"""

import os
os.environ["FORCE_HEADLESS"] = "1"

import io, time
import numpy as np
import torch
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d.art3d import Poly3DCollection
from PIL import Image

from On_line_PI_one_drone_env1 import (
    Config, OBSTACLES, BoxObstacle, SphereObstacle,
    train_ppo, rollout_policy_fn, trajectory_cost,
    PolicyWithTrajectory, run_rollout_iteration,
    generate_perturbation_data, train_residual_nn,
    draw_box_3d, draw_sphere_3d,
)

"""# Problem Definition & Algorithm"""

# ══════════════════════════════════════════════════════════════════════════════
# Run full PI and collect trajectories
# ══════════════════════════════════════════════════════════════════════════════

def run_pi():
    cfg = Config()
    np.random.seed(42)
    torch.manual_seed(42)

    print("Training PPO...")
    ppo_policy = train_ppo(cfg)
    traj_0, ctrl_0 = rollout_policy_fn(
        lambda x, k: ppo_policy.act(x, cfg, deterministic=True)[0], cfg)
    cost_0 = trajectory_cost(traj_0, ctrl_0, cfg)
    print(f"[Iter 0] cost={cost_0:.2f}")

    all_trajs = [traj_0]
    all_costs = [cost_0]
    current_policy = PolicyWithTrajectory(traj_0, ctrl_0, None, cfg)
    no_improve = 0

    for it in range(1, cfg.n_policy_iters + 1):
        new_traj, new_ctrl, n_imp, _, rt = run_rollout_iteration(current_policy, cfg)
        new_cost = trajectory_cost(new_traj, new_ctrl, cfg)
        print(f"[Iter {it}] cost={new_cost:.2f} (Δ={new_cost-all_costs[-1]:+.2f})")

        perturb = generate_perturbation_data(new_traj, new_ctrl, cfg)
        resnn = train_residual_nn(new_traj, new_ctrl, perturb, cfg)
        current_policy = PolicyWithTrajectory(new_traj, new_ctrl, resnn, cfg)

        all_trajs.append(new_traj)
        all_costs.append(new_cost)
        if n_imp == 0:
            no_improve += 1
        else:
            no_improve = 0
        if no_improve >= 2:
            break

    return all_trajs, all_costs, cfg

"""# Drawing Nodes & Animation"""

# ══════════════════════════════════════════════════════════════════════════════
# Drone drawing (Crazyflie quad-rotor)
# ══════════════════════════════════════════════════════════════════════════════

def draw_crazyflie(ax, pos, size=0.18):
    """Draw the Crazyflie at position pos."""
    cx, cy, cz = pos
    arm_len = size
    prop_r = size * 0.7
    arms = [
        np.array([1, 1, 0]) / np.sqrt(2),
        np.array([1, -1, 0]) / np.sqrt(2),
        np.array([-1, 1, 0]) / np.sqrt(2),
        np.array([-1, -1, 0]) / np.sqrt(2),
    ]
    for arm_dir in arms:
        tip = np.array([cx, cy, cz]) + arm_len * arm_dir
        ax.plot([cx, tip[0]], [cy, tip[1]], [cz, tip[2]],
                color="#222222", linewidth=2.5, solid_capstyle="round",
                zorder=15)
        theta = np.linspace(0, 2 * np.pi, 24)
        ax.plot(tip[0] + prop_r * np.cos(theta),
                tip[1] + prop_r * np.sin(theta),
                np.full(24, tip[2]),
                color="#1565c0", linewidth=1.4, alpha=0.85, zorder=15)
    # Body
    ax.scatter([cx], [cy], [cz], color="#1565c0", s=45,
               edgecolor="#0d47a1", linewidth=0.6, zorder=16)


# ══════════════════════════════════════════════════════════════════════════════
# Scene setup
# ══════════════════════════════════════════════════════════════════════════════

def setup_scene(ax, cfg):
    for obs in OBSTACLES:
        if isinstance(obs, BoxObstacle):
            draw_box_3d(ax, obs.center, obs.half_size,
                        color="#6b7280", alpha=0.28, edgecolor="#374151")
        elif isinstance(obs, SphereObstacle):
            draw_sphere_3d(ax, obs.center, obs.radius,
                           color="#e11d48", alpha=0.22)
    # Goal
    draw_box_3d(ax, cfg.goal_center, cfg.goal_half_size,
                color="#22c55e", alpha=0.28, edgecolor="#15803d")
    # Start marker
    ax.scatter(*cfg.x0[:3], s=45, color="#0b5394",
               edgecolor="white", linewidth=0.8, zorder=12,
               label="Start")

    ax.set_xlim(-2.8, 3.5)
    ax.set_ylim(-2.8, 3.5)
    ax.set_zlim(-0.8, 2.0)
    ax.set_box_aspect((1.0, 1.0, 0.5))
    ax.view_init(elev=26, azim=-55)
    ax.set_xlabel("X", fontsize=10, labelpad=4)
    ax.set_ylabel("Y", fontsize=10, labelpad=4)
    ax.set_zlabel("Z", fontsize=10, labelpad=4)
    ax.tick_params(axis="both", labelsize=7, pad=1)
    ax.grid(True, alpha=0.15)
    try:
        ax.xaxis.pane.set_facecolor((0.97, 0.97, 0.97, 0.3))
        ax.yaxis.pane.set_facecolor((0.97, 0.97, 0.97, 0.3))
        ax.zaxis.pane.set_facecolor((0.97, 0.97, 0.97, 0.3))
    except Exception:
        pass


def fig_to_pil(fig, dpi=110):
    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=dpi, facecolor=fig.get_facecolor())
    buf.seek(0)
    return Image.open(buf).convert("RGB")

# ══════════════════════════════════════════════════════════════════════════════
# Animation: drone flies along trajectory
# ══════════════════════════════════════════════════════════════════════════════

def generate_flight_animation(
    all_trajs, all_costs, cfg,
    show_iters=None,
    output="drone_flight_animation.gif",
    dpi=110,
    step_skip=2,        # show every Nth timestep to keep GIF manageable
    ms_per_step=120,    # ms per drone-position frame
    ms_hold_start=1500, # ms to hold the title card before flight
    ms_hold_end=2000,   # ms to hold after drone reaches goal
):
    n_total = len(all_trajs)
    if show_iters is None:
        show_iters = [0, min(4, n_total - 1), n_total - 1]
    show_iters = sorted(set(i for i in show_iters if i < n_total))

    # Colors per iteration segment
    ITER_COLORS = {
        show_iters[0]: "#d62728",   # red  — initial PPO
    }
    if len(show_iters) > 2:
        ITER_COLORS[show_iters[1]] = "#ff7f0e"  # orange — mid
    if len(show_iters) > 1:
        ITER_COLORS[show_iters[-1]] = "#1565c0"  # blue — final

    # For iterations not in the map, default
    for it in show_iters:
        if it not in ITER_COLORS:
            ITER_COLORS[it] = "#d62728"

    TRAIL_COLORS = {
        show_iters[0]: "#ef9a9a",
    }
    if len(show_iters) > 2:
        TRAIL_COLORS[show_iters[1]] = "#ffcc80"
    if len(show_iters) > 1:
        TRAIL_COLORS[show_iters[-1]] = "#90caf9"
    for it in show_iters:
        if it not in TRAIL_COLORS:
            TRAIL_COLORS[it] = "#ef9a9a"

    print(f"\nAnimating iterations: {show_iters}")

    fig = plt.figure(figsize=(9, 6.5))
    fig.patch.set_facecolor("white")

    pil_frames = []
    durations = []

    for iter_idx in show_iters:
        traj = all_trajs[iter_idx]
        arr = np.array(traj)  # shape (N+1, 12)
        cost = all_costs[iter_idx]
        color = ITER_COLORS[iter_idx]
        trail_color = TRAIL_COLORS[iter_idx]
        n_pts = len(arr)

        # Which timesteps to render
        steps = list(range(0, n_pts, step_skip))
        if steps[-1] != n_pts - 1:
            steps.append(n_pts - 1)

        # Iter label
        if iter_idx == 0:
            iter_label = "Iteration 0 (PPO)"
        elif iter_idx == len(all_trajs) - 1:
            iter_label = f"Iteration {iter_idx} (converged)"
        else:
            iter_label = f"Iteration {iter_idx}"

        for frame_i, t in enumerate(steps):
            fig.clf()
            ax = fig.add_subplot(111, projection="3d")
            fig.subplots_adjust(left=0.0, right=1.0, bottom=0.02, top=0.92)

            setup_scene(ax, cfg)

            # Draw previous iterations' full trajectories as thin faded lines
            for prev_it in show_iters:
                if prev_it >= iter_idx:
                    break
                prev_arr = np.array(all_trajs[prev_it])
                ax.plot(prev_arr[:, 0], prev_arr[:, 1], prev_arr[:, 2],
                        color=TRAIL_COLORS[prev_it], alpha=0.35,
                        linewidth=1.2, linestyle="--", zorder=2)

            # Trail up to current position
            if t > 0:
                trail = arr[:t+1]
                ax.plot(trail[:, 0], trail[:, 1], trail[:, 2],
                        color=color, linewidth=2.0, alpha=0.7, zorder=4)

            # Faded future path (thin, dashed)
            if t < n_pts - 1:
                future = arr[t:]
                ax.plot(future[:, 0], future[:, 1], future[:, 2],
                        color=trail_color, linewidth=1.0, alpha=0.35,
                        linestyle=":", zorder=3)

            # Drone at current position
            pos = arr[t, :3]
            draw_crazyflie(ax, pos, size=0.18)

            # Title
            fig.suptitle(iter_label, fontsize=13, fontweight="bold",
                         y=0.96, color="#1A1A1A")

            # Cost and time step
            time_val = t * cfg.dt
            info = f"J = {cost:.2f}    t = {time_val:.1f}s  (step {t}/{n_pts-1})"
            ax.text2D(0.5, 0.02, info, transform=ax.transAxes,
                      ha="center", fontsize=10, fontweight="bold",
                      color="#2255AA")

            pil_frames.append(fig_to_pil(fig, dpi=dpi))

            # Timing
            if frame_i == 0:
                durations.append(ms_hold_start)
            elif t == n_pts - 1:
                durations.append(ms_hold_end)
            else:
                durations.append(ms_per_step)

        print(f"  {iter_label}: {len(steps)} frames rendered")

    plt.close(fig)

    # Assemble GIF
    pil_frames[0].save(
        output,
        save_all=True,
        append_images=pil_frames[1:],
        duration=durations,
        loop=0,
    )
    print(f"\nSaved: {output}  ({len(pil_frames)} frames, "
          f"{sum(durations)/1000:.1f}s total)")

"""# GIF Generation"""

if __name__ == "__main__":
    all_trajs, all_costs, cfg = run_pi()

    n = len(all_trajs)
    show = [0, min(4, n - 1), n - 1]

    generate_flight_animation(
        all_trajs, all_costs, cfg,
        show_iters=show,
        output="drone_flight_animation.gif",
        step_skip=2,
        ms_per_step=120,
        ms_hold_start=1500,
        ms_hold_end=2500,
    )